### ISSUE TITLE
UI for editing YouTube content

### ISSUE THREAD

**Issue by kauffj** [lbryio/ytsync#31]
@nikooo777 how feasible would it be to allow @robvsmith and other growth team members to edit YouTube publishes and channels? Ideally via the same UI in app.

**Comment by nikooo777** [comment]
I discussed this briefly with Grin today. If I understand it right, what we want to have is a way to add tags or other properties and mark a video as "dirty" so that ytsync picks it up and "updates" it.

It would take changes in both ytsync and internal-apis as right now channels are processed by channel changes, not video changes (as in, the channel is market as "dirty" and ytsync goes through the whole channel).

I don't think having it done through the app would make much sense as we'd technically want to have the claims visible in the app and thus be able to edit the claim straight away from there, not through ytsync.
However an additional entry in api forms to handle tags (and not sure what else) could be doable.
